spring:
  application:
    name: simple-spring-boot-agent
  ai:
    bedrock:
      aws:
        region: ap-south-1
      converse:
        chat:
          options:
             model: global.amazon.nova-2-lite-v1:0
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

agentcore:
  memory:
    memory_id: memory_27vql-Vl7nIoHdf6
    total-events-limit: 100
    default-session: default
    page-size: 50
    ignore-unknown-roles: false
  browser: # Local browser mode (default) — uses Playwright
    mode: local #agentcore # Remote mode — uses AgentCore Browser service
    viewport-height: 1456
    viewport-width: 819
    max-content-length: 10000


app:
  output-dir: screenshots

management:
  endpoints:
    web:
      exposure:
        exclude: health

# logging properties
logging:
  level:
    org:
      springaicommunity:
        agentcore: DEBUG
    root: INFO


